[files]
extend-exclude = [
    "ui/src/components/creative-tim/blocks/*.tsx",
    "chunk-your-tools.cdx.json",
    "chunk-your-tools.snyk.json",
    ]

[default.extend-words]
# Don't correct the surname "EIN"
Bui = "Bui"
# codespell ignore token in pre-commit config
FO = "FO"
Provices = "Provices"
